### ISSUE TITLE
update menu.js working???

### ISSUE THREAD

**Issue by Anshuljai** [Kokoronationz/kuriyama#8]
the fake thumbnail solves marker not found error....please reply 😏
@Kokoronationz

**Comment by Kokoronationz** [comment]
> the fake thumbnail solves marker not found error....please reply 😏
> @Kokoronationz 

this works

**Comment by Anshuljai** [comment]
so no error after inputing fake thumbnail???


`no marker not found error at decode scan jimp module`

**Comment by Anshuljai** [comment]
@Kokoronationz
