### ISSUE TITLE
cara hide menu

### ISSUE THREAD

**Issue by xaryow** [Kokoronationz/kuriyama#9]
cara biar hanya beberapa menu yang keluar ketika #menu gimana ya?
contohnya ketika ada user yg pake #menu hanya keluar menu group,fun,game doang

**Comment by ghost** [comment]
> cara biar hanya beberapa menu yang keluar ketika #menu gimana ya?
> contohnya ketika ada user yg pake #menu hanya keluar menu group,fun,game doang

Kasih //
Contoh //game

**Comment by xaryow** [comment]
udah di tambah // di awal tetep muncul

**Comment by ghost** [comment]
> udah di tambah // di awal tetep muncul

Bug update menu tuh, gua masih pake yg lama soalnya
